### ISSUE TITLE
Preload, defer attributes

### ISSUE THREAD

**Issue by th-thomas** [RealOrangeOne/django-sri#64]
Hi,
Would it be possible to make django-sri work with preload, defer (or async) attribute ?

**Comment by RealOrangeOne** [comment]
It would, although for compatibility, it'd have to be opt-in, as it is in browsers anyway.

I'd definitely welcome a PR adding this support.

In the mean time, you can use the [`sri_integrity_static`](https://github.com/RealOrangeOne/django-sri#just-the-integrity-value) template tag to achieve this

**Comment by th-thomas** [comment]
I managed to make it work using `sri_integrity_static` as you suggested. Thank you!
I've also made a few modifications (backwards compatible) to your module and submitted a pull request. I hope my code is not too bad looking, and more important, has no bugs!

**Comment by RealOrangeOne** [comment]
Fixed in #69
