### ISSUE TITLE
Omit "type" attribute from script tags

### ISSUE THREAD

**Issue by hugorodgerbrown** [RealOrangeOne/django-sri#68]
When validating the output with the W3C validator a warning is raised for "Warning: The type attribute is unnecessary for JavaScript resources."

It would be good to be able to suppress this in the output?

**Comment by RealOrangeOne** [comment]
Looking at https://html.spec.whatwg.org/multipage/scripting.html#the-script-element, you are correct:

> Omitting the attribute, setting it to the empty string, or setting it to a [JavaScript MIME type essence match](https://mimesniff.spec.whatwg.org/#javascript-mime-type-essence-match), means that the script is a [classic script](https://html.spec.whatwg.org/multipage/webappapis.html#classic-script), to be interpreted according to the Java[Script](https://tc39.es/ecma262/#prod-Script) Script top-level production. Classic scripts are affected by the [async](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-async) and [defer](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-defer) attributes, but only when the [src](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-src) attribute is set. Authors should omit the [type](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-type) attribute instead of redundantly setting it.

I'd be open for a PR to remove the type attribute.
