### ISSUE TITLE
Add ability to manage cache timeout with settings

### ISSUE THREAD

**Issue by hugorodgerbrown** [RealOrangeOne/django-sri#95]
This may be very niche, but we have a situation where we need the local cache to have a very short timeout. If we could pass this in as a setting (it's for local dev only), that would be really helpful. I'll raise a PR.

**Comment by hugorodgerbrown** [comment]
Ignore me - it's easy enough to set the "sri" cache to the dummy backend if you have the ability to edit local settings:

```python
# main settings
CACHES = {
    "default": {
        "BACKEND": "...",
    }
}

# local settings - add / update "sri" cache
CACHES["sri"] = {"BACKEND": "django.core.cache.backends.dummy.DummyCache"}
```

**Comment by RealOrangeOne** [comment]
Using `DummyCache` defeats the point of having a cache (which may be what you want). If you just want to tweak the timeout, you can set the `TIMEOUT` key in the cache to whatever you need it to be
